left_plane: [-0.00301767, -0.999989, -0.00370002, 11.6785]

right_plane: [-0.000907324, -0.999765, -0.0216685, -0.350168]

back_plane: [0.971066, 0.237772, 0.0222419, -32.2739]

# rotate lidar data to map,but rotate the map to the lidar acturally when calculate volume
# folloing params is raw data from lidar to map
YPR: [-72,23.0,0]
xyz: [104,3.5,6.0]

#fix lidar rotation
#lidar_YPR: [12,23,0]
#lidar_xyz: [0,0,10.4]
lidar_YPR: [0,0,0]
lidar_xyz: [0,0,3.5]

left_2_right_YPR: [-36.0,0,0]
left_2_right_xyz: [6.6,8.0,0]

load_map: True
add_cloud: True
hand_adjust: False
align_: False
cloud_dir: "/home/hjx/based_point_segment_ws/b_pcd/small_2.pcd"